// src/App.tsx
import { useEffect, useState, useRef } from 'react';
import { invoke } from '@tauri-apps/api/core';
import { listen } from '@tauri-apps/api/event';
import type { AppConfig, UsageData } from './types/api';
import ConfigPanel from './components/ConfigPanel';
import UsageDisplay from './components/UsageDisplay';
import './App.css';

export default function App() {
  const [config, setConfig] = useState<AppConfig | null>(null);
  const [usage, setUsage] = useState<UsageData | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [showConfig, setShowConfig] = useState(true);
  const unlistensRef = useRef<(() => Promise<void>)[]>([]);

  useEffect(() => {
    let mounted = true;
    const unlistens: (() => Promise<void>)[] = [];

    // 加载配置
    invoke<AppConfig>("get_config").then(cfg => {
      if (mounted) {
        setConfig(cfg);
        // 如果有配置且有效，默认显示用量页面
        if (cfg && cfg.token && cfg.organization && cfg.project) {
          setShowConfig(false);
        }
      }
    });

    // 先设置事件监听器（确保不丢失后续事件）
    listen<UsageData>("usage-update", (event) => {
      if (mounted) {
        setUsage(event.payload);
        setError(null);
      }
    }).then(unlisten => unlistens.push(unlisten));

    listen<string>("usage-error", (event) => {
      if (mounted) {
        setError(event.payload);
      }
    }).then(unlisten => unlistens.push(unlisten));

    listen("tray-click", () => {
      if (mounted) {
        setShowConfig(prev => !prev);
      }
    }).then(unlisten => unlistens.push(unlisten));

    // 保存 unlisten 函数
    unlistensRef.current = unlistens;

    // 然后获取当前状态（在监听器设置之后）
    invoke<UsageData | null>("get_current_usage").then(data => {
      if (mounted && data) {
        setUsage(data);
      }
    });

    invoke<string | null>("get_current_error").then(err => {
      if (mounted && err) {
        setError(err);
      }
    });

    return () => {
      mounted = false;
      // 清理所有监听器
      unlistensRef.current.forEach(unlisten => unlisten());
    };
  }, []);

  const handleSave = (newConfig: AppConfig) => {
    setConfig(newConfig);
  };

  return (
    <div className="container">
      {showConfig || !config ? (
        <ConfigPanel
          config={config}
          onSave={handleSave}
          onClose={() => setShowConfig(false)}
        />
      ) : (
        <UsageDisplay
          usage={usage}
          error={error}
          onConfig={() => setShowConfig(true)}
        />
      )}
    </div>
  );
}

// src/App.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import ConfigPanel from "./components/ConfigPanel.svelte";
  import UsageDisplay from "./components/UsageDisplay.svelte";
  import { invoke } from "@tauri-apps/api/core";
  import { listen } from "@tauri-apps/api/event";

  let config: any = null;
  let usage: any = null;
  let error: string | null = null;
  let showConfig = true;

  onMount(async () => {
    // 加载配置
    config = await invoke("get_config");

    // 先设置事件监听器（确保不丢失后续事件）
    const unlistenUsage = await listen("usage-update", (event: any) => {
      usage = event.payload;
      error = null;
    });

    const unlistenError = await listen("usage-error", (event: any) => {
      error = event.payload;
    });

    const unlistenTray = await listen("tray-click", () => {
      showConfig = !showConfig;
    });

    // 然后获取当前状态（在监听器设置之后）
    usage = await invoke("get_current_usage");
    error = await invoke("get_current_error");

    // 如果有配置且有效，默认显示用量页面
    if (config && config.token && config.organization && config.project) {
      showConfig = false;
    }

    return () => {
      unlistenUsage();
      unlistenError();
      unlistenTray();
    };
  });

  function handleSave(newConfig: any) {
    config = newConfig;
  }
</script>

<div class="container">
  {#if showConfig || !config}
    <ConfigPanel {config} onSave={handleSave} onClose={() => showConfig = false} />
  {:else}
    <UsageDisplay {usage} {error} onConfig={() => showConfig = true} />
  {/if}
</div>

<style>
  :global(body) {
    margin: 0;
    padding: 0;
    background: #f5f5f5;
  }

  .container {
    width: 100%;
    height: 100vh;
    overflow-y: auto;
  }
</style>
